version: '3'
services:
  php70:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        php_version: "7.0"
    image: pecl-memcache-issue-23:php70
    ports:
      - "8001:8000"
    volumes:
      - .:/code
  php71:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        php_version: "7.1"
    image: pecl-memcache-issue-23:php71
    ports:
      - "8002:8000"
    volumes:
      - .:/code
